-- Ensure you have run seed-families.sql before running this!
-- This script will migrate your 13 hardcoded Audio Breaths into the database.
-- They will not have audio_url values yet - you can upload the .wav files manually in the Admin Portal!

INSERT INTO audio_breaths (id, family_id, title, intro, description, approach, use_when, science_text, science_source, spiritual_text, spiritual_source, audio_url, sort_order) VALUES
('anxiety-downshift', 'calm-me-down', 'Anxiety Downshift', 'Anxiety is the body moving into speed when it senses uncertainty, pressure, or threat.', '', 'This breath meets the body in this state, slowing the exhale and softening tension so the nervous system can settle naturally.', '["Your thoughts feel fast or spiralling", "Your chest feels tight or breathing feels shallow", "Your body feels restless, keyed up, or on edge", "You need relief without analysis or effort"]'::jsonb, 'Slow exhales activate the vagus nerve, slowing the body''s stress response, calming the mind, and bringing the body back to balance.', 'Porges, S. W. (2011). Polyvagal Theory. W.W. Norton & Company.', 'The practice of breathing slowly out mirrors the spiritual concept of surrender — letting go of control and allowing the body to return to its natural rhythm. In this moment, we aren''t trying to fix the anxiety, but simply allowing it to move through, creating space for calm.', 'Brach, T. (2003). Radical Acceptance. Bantam Books.', '', 1),
('emergency-grounding', 'calm-me-down', 'Emergency Grounding', 'When everything feels too fast.', 'A grounding breath for moments of overwhelm or panic.', 'This breath uses tactile awareness and slow exhales to anchor you back to the present moment.', '["You feel disconnected from your body", "Panic is rising", "You need to come back to the present quickly", "Thoughts are racing uncontrollably"]'::jsonb, 'Grounding techniques activate the prefrontal cortex, helping to override the amygdala''s fear response. Combined with slow breathing, this creates a powerful calming effect.', 'Van der Kolk, B. (2014). The Body Keeps the Score.', 'In many traditions, the earth represents stability and support. Grounding is an act of remembering that we are held.', 'Levine, P. (2010). In an Unspoken Voice.', '', 2),
('social-nerves-reset', 'calm-me-down', 'Social Nerves Reset', 'Before you walk in.', 'A quick reset for social anxiety or performance nerves.', 'This breath settles the nervous system before social situations without numbing your aliveness.', '["Before a meeting or presentation", "Before entering a social gathering", "When you feel judged or watched", "Before a difficult conversation"]'::jsonb, 'Social anxiety triggers the same fight-or-flight response as physical threats. Breath regulation helps the body distinguish between real danger and social discomfort.', 'Porges, S. W. (2011). Polyvagal Theory.', 'You belong here. This breath is a reminder that your presence is enough.', 'Brown, B. (2010). The Gifts of Imperfection.', '', 3),
('before-you-react', 'emotional-regulation', 'Before You React', 'A pause before action.', 'For when you feel the urge to say or do something you might regret.', 'This breath creates a gap between stimulus and response, allowing wisdom to enter.', '["You feel triggered or defensive", "Anger is rising", "You want to lash out", "You need to respond rather than react"]'::jsonb, 'The pause created by conscious breathing allows the prefrontal cortex to engage, improving decision-making and reducing impulsive reactions.', 'Siegel, D. (2010). Mindsight.', 'Between stimulus and response, there is a space. In that space is our power to choose.', 'Frankl, V. (1946). Man''s Search for Meaning.', '', 4),
('overwhelm-unclench', 'emotional-regulation', 'Overwhelm Unclench', 'When everything feels like too much.', 'A breath to release the grip of overwhelm.', 'This breath helps you soften the physical tension that accompanies emotional overwhelm.', '["You feel frozen by too many demands", "Your shoulders are up by your ears", "You don''t know where to start", "Everything feels equally urgent"]'::jsonb, 'Chronic overwhelm creates physical tension patterns. Conscious breathing interrupts this cycle and signals safety to the body.', 'Nagoski, E. (2019). Burnout.', 'You cannot pour from an empty cup. This breath is an act of self-preservation.', 'Neff, K. (2011). Self-Compassion.', '', 5),
('shame-release', 'emotional-regulation', 'Shame Release', 'Shame shrinks us. This breath expands.', 'A gentle breath for moments when shame feels consuming.', 'This breath creates space around shame without trying to fix or analyze it.', '["You feel small or unworthy", "You''re replaying a mistake", "Self-criticism is loud", "You need to remember your wholeness"]'::jsonb, 'Shame activates the freeze response. Breath work can help move the body out of immobility and back into connection.', 'Brown, B. (2012). Daring Greatly.', 'You are not your mistakes. You are the awareness that notices them.', 'Tolle, E. (1999). The Power of Now.', '', 6),
('grief-companion', 'emotional-regulation', 'Grief Companion', 'Grief needs presence, not fixing.', 'A breath to be with grief without being consumed by it.', 'This breath offers gentle accompaniment through waves of grief.', '["Grief feels overwhelming", "You need to cry but feel stuck", "You''re missing someone or something", "You need permission to feel"]'::jsonb, 'Suppressing grief creates physical and emotional strain. Breath work can facilitate healthy processing of loss.', 'Kessler, D. (2019). Finding Meaning.', 'Grief is love with nowhere to go. This breath gives it space to flow.', 'Rumi', '', 7),
('morning-spark', 'motivate-me', 'Morning Spark', 'Wake your body gently.', 'An energizing breath to start your day with intention.', 'This breath gradually increases energy without jarring the system.', '["You feel groggy upon waking", "You need motivation to start", "Energy feels flat or low", "You want to set an intentional tone for the day"]'::jsonb, 'Controlled breathing with slightly longer inhales activates the sympathetic nervous system gently, promoting alertness.', 'Huberman, A. (2021). Huberman Lab Podcast.', 'Each morning is a new beginning. This breath welcomes the day.', 'Thich Nhat Hanh', '', 8),
('confidence-charge-up', 'motivate-me', 'Confidence Charge-Up', 'Stand a little taller.', 'A breath to access your natural confidence.', 'This breath uses posture and breath to shift your internal state.', '["You need a confidence boost", "Before an important moment", "You feel small or diminished", "You want to show up fully"]'::jsonb, 'Research shows that embodied practices like breath work and posture changes can shift hormone levels and mood.', 'Cuddy, A. (2015). Presence.', 'Your confidence is not arrogance. It is remembering who you really are.', 'Williamson, M. (1992). A Return to Love.', '', 9),
('joy-amplifier', 'motivate-me', 'Joy Amplifier', 'Let the good stay longer.', 'A breath to extend and deepen positive feelings.', 'This breath helps you savor good moments instead of rushing past them.', '["Something good just happened", "You want to extend a positive feeling", "Gratitude is present", "You tend to rush past good moments"]'::jsonb, 'The negativity bias means we must actively practice savoring positive experiences to rewire the brain for well-being.', 'Hanson, R. (2013). Hardwiring Happiness.', 'Joy is your birthright. This breath helps you claim it.', 'Ruiz, D. M. (1997). The Four Agreements.', '', 10),
('creative-spark', 'motivate-me', 'Creative Spark', 'Unlock what wants to flow.', 'A breath to open creative channels.', 'This breath releases the tension that blocks creative flow.', '["You feel creatively blocked", "Before writing, creating, or brainstorming", "Perfectionism is stopping you", "You need to access playfulness"]'::jsonb, 'Relaxed alertness, achieved through breath work, is the optimal state for creative thinking.', 'Csikszentmihalyi, M. (1990). Flow.', 'Creativity is not something you have. It is something you allow.', 'Gilbert, E. (2015). Big Magic.', '', 11),
('single-task-focus', 'help-me-focus', 'Single-Task Focus', 'One thing at a time.', 'A breath to narrow attention to what matters now.', 'This breath clears mental clutter and sharpens focus.', '["Your attention is scattered", "You keep getting distracted", "You need to concentrate deeply", "Multiple things are pulling at you"]'::jsonb, 'Focused attention breathing increases activity in the prefrontal cortex, improving concentration and working memory.', 'Goleman, D. (2013). Focus.', 'Where attention goes, energy flows. This breath directs your life force.', 'Judith, A. (2004). Eastern Body, Western Mind.', '', 12),
('boundary-setting', 'help-me-focus', 'Boundary Setting', 'This is where I end and you begin.', 'A breath to strengthen your energetic boundaries.', 'This breath helps you distinguish your energy from others''.', '["You''ve absorbed others'' emotions", "You need to say no", "You feel depleted by others", "You need to reclaim your energy"]'::jsonb, 'Breath awareness helps activate the body''s sense of self, supporting healthy boundaries.', 'Pert, C. (1997). Molecules of Emotion.', 'Boundaries are not walls. They are the fences that allow for healthy gardens.', 'Cloud, H. (1992). Boundaries.', '', 13),
('transition-support', 'help-me-focus', 'Transition Support', 'Between what was and what''s next.', 'A breath for moving between roles, tasks, or moments.', 'This breath creates a clear transition, allowing you to arrive fully.', '["Between work and home", "After a difficult interaction", "Before entering a new space", "When switching between roles"]'::jsonb, 'Transition rituals help the brain release one context and prepare for another, reducing cognitive residue.', 'Newport, C. (2016). Deep Work.', 'Every ending is a beginning. This breath honors both.', 'Bridges, W. (1980). Transitions.', '', 14)
ON CONFLICT (id) DO NOTHING;
